export const roles = [
  "ADMIN",
  "PHARMACIST",
  "PHARMACIST_IN_CHARGE",
  "INVENTORY_MANAGER",
  "TECHNICIAN",
  "INTERN",
  "CASHIER",
  "AUDITOR",
] as const;

export type Role = (typeof roles)[number];

export const permissions = [
  "patient:read",
  "patient:write",
  "prescription:read",
  "prescription:enter",
  "prescription:edit",
  "prescription:process",
  "prescription:verify",
  "prescription:sell",
  "prescription:emergency",
  "clinical:document",
  "document:read",
  "document:upload",
  "document:annotate",
  "inventory:read",
  "inventory:write",
  "inventory:correct",
  "thirdparty:read",
  "thirdparty:write",
  "thirdparty:override",
  "product:compliance",
  "user:manage",
  "audit:read",
  "system:backup",
] as const;

export type Permission = (typeof permissions)[number];

export const rolePermissions: Record<Role, readonly Permission[]> = {
  ADMIN: permissions,
  PHARMACIST_IN_CHARGE: [
    "patient:read", "patient:write",
    "prescription:read", "prescription:enter", "prescription:edit",
    "prescription:process", "prescription:verify", "prescription:sell",
    "prescription:emergency", "clinical:document",
    "document:read", "document:upload", "document:annotate",
    "inventory:read", "inventory:write", "inventory:correct",
    "thirdparty:read", "thirdparty:write", "thirdparty:override",
    "product:compliance", "user:manage", "audit:read",
  ],
  INVENTORY_MANAGER: [
    "inventory:read", "inventory:write", "inventory:correct",
    "product:compliance",
  ],
  PHARMACIST: [
    "patient:read",
    "patient:write",
    "prescription:read",
    "prescription:enter",
    "prescription:edit",
    "prescription:process",
    "prescription:verify",
    "prescription:sell",
    "prescription:emergency",
    "clinical:document",
    "document:read",
    "document:upload",
    "document:annotate",
    "inventory:read",
    "inventory:write",
    "inventory:correct",
    "thirdparty:read",
    "thirdparty:write",
    "thirdparty:override",
    "product:compliance",
    "audit:read",
  ],
  TECHNICIAN: [
    "patient:read",
    "patient:write",
    "prescription:read",
    "prescription:enter",
    "prescription:edit",
    "prescription:process",
    "prescription:sell",
    "document:read",
    "document:upload",
    "document:annotate",
    "inventory:read",
    "inventory:write",
    "thirdparty:read",
    "thirdparty:write",
  ],
  INTERN: [
    "patient:read",
    "patient:write",
    "prescription:read",
    "prescription:enter",
    "prescription:edit",
    "prescription:process",
    "document:read",
    "document:upload",
    "document:annotate",
    "inventory:read",
    "thirdparty:read",
  ],
  CASHIER: ["patient:read", "prescription:read", "prescription:sell"],
  AUDITOR: ["audit:read"],
};

export function roleHasPermission(role: Role, permission: Permission) {
  return rolePermissions[role].includes(permission);
}
