"""Add synthetic scheduled fills with idempotent start and refill review

Revision ID: 17d52add635c
Revises: 230691d35edd
Create Date: 2026-10-08 21:01:59.124325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17d52add635c'
down_revision: Union[str, Sequence[str], None] = '230691d35edd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('py_scheduled_fills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('prescription_id', sa.String(length=36), nullable=False),
    sa.Column('due_date', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('started_by_id', sa.String(length=36), nullable=True),
    sa.Column('cancelled_by_id', sa.String(length=36), nullable=True),
    sa.Column('fill_id', sa.String(length=36), nullable=True),
    sa.Column('cancelled_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('PENDING', 'STARTED', 'CANCELLED')", name='ck_py_scheduled_fills_status'),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['py_staff.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['py_staff.id'], ),
    sa.ForeignKeyConstraint(['fill_id'], ['py_fills.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['py_prescriptions.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['py_sites.id'], ),
    sa.ForeignKeyConstraint(['started_by_id'], ['py_staff.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fill_id'),
    sa.UniqueConstraint('site_id', 'idempotency_key', name='uq_py_scheduled_fills_key')
    )
    op.create_index(op.f('ix_py_scheduled_fills_prescription_id'), 'py_scheduled_fills', ['prescription_id'], unique=False)
    op.create_index(op.f('ix_py_scheduled_fills_site_id'), 'py_scheduled_fills', ['site_id'], unique=False)
    op.create_index('ux_py_scheduled_fills_one_pending_rx', 'py_scheduled_fills', ['prescription_id'], unique=True, sqlite_where=sa.text("status = 'PENDING'"), postgresql_where=sa.text("status = 'PENDING'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Never drop clinical scheduling history automatically."""
    raise RuntimeError("Scheduled-fill downgrade requires reviewed backup and restore")
