"""site scoped provider directory identifiers contacts addresses

Revision ID: 230691d35edd
Revises: 63ff0bb0a4d8
Create Date: 2026-10-08 20:48:36.781636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '230691d35edd'
down_revision: Union[str, Sequence[str], None] = '63ff0bb0a4d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('py_provider_addresses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('prescriber_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('line1', sa.String(length=150), nullable=False),
    sa.Column('line2', sa.String(length=150), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('postal_code', sa.String(length=30), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prescriber_id'], ['py_prescribers.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['py_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_py_provider_addresses_prescriber_id'), 'py_provider_addresses', ['prescriber_id'], unique=False)
    op.create_index(op.f('ix_py_provider_addresses_site_id'), 'py_provider_addresses', ['site_id'], unique=False)
    op.create_index('ux_py_provider_address_primary', 'py_provider_addresses', ['prescriber_id'], unique=True, sqlite_where=sa.text('is_primary = 1 AND active = 1'), postgresql_where=sa.text('is_primary = true AND active = true'))
    op.create_table('py_provider_contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('prescriber_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=15), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('value', sa.String(length=80), nullable=False),
    sa.Column('normalized', sa.String(length=80), nullable=False),
    sa.Column('extension', sa.String(length=20), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prescriber_id'], ['py_prescribers.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['py_sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prescriber_id', 'kind', 'normalized', 'extension')
    )
    op.create_index(op.f('ix_py_provider_contacts_prescriber_id'), 'py_provider_contacts', ['prescriber_id'], unique=False)
    op.create_index(op.f('ix_py_provider_contacts_site_id'), 'py_provider_contacts', ['site_id'], unique=False)
    op.create_index('ux_py_provider_contact_primary', 'py_provider_contacts', ['prescriber_id', 'kind'], unique=True, sqlite_where=sa.text('is_primary = 1 AND active = 1'), postgresql_where=sa.text('is_primary = true AND active = true'))
    op.create_table('py_provider_identifiers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('prescriber_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('number', sa.String(length=80), nullable=False),
    sa.Column('normalized', sa.String(length=80), nullable=False),
    sa.Column('jurisdiction', sa.String(length=10), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prescriber_id'], ['py_prescribers.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['py_sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prescriber_id', 'type', 'normalized', 'jurisdiction')
    )
    op.create_index(op.f('ix_py_provider_identifiers_prescriber_id'), 'py_provider_identifiers', ['prescriber_id'], unique=False)
    op.create_index(op.f('ix_py_provider_identifiers_site_id'), 'py_provider_identifiers', ['site_id'], unique=False)
    op.create_index('ux_py_provider_identifier_primary', 'py_provider_identifiers', ['prescriber_id', 'type', 'jurisdiction'], unique=True, sqlite_where=sa.text('is_primary = 1 AND active = 1'), postgresql_where=sa.text('is_primary = true AND active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Do not delete directory records as an automatic schema downgrade."""
    raise RuntimeError("Directory downgrade disabled: use a reviewed backup/restore procedure")
