"""initial isolated Python schema

Revision ID: 63ff0bb0a4d8
Revises: 
Create Date: 2026-10-08 20:39:30.321063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63ff0bb0a4d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('py_drugs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('strength', sa.String(length=70), nullable=False),
    sa.Column('dosage_form', sa.String(length=70), nullable=False),
    sa.Column('controlled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_py_drugs_name'), 'py_drugs', ['name'], unique=False)
    op.create_table('py_sites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('py_patients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['py_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_py_patients_last_name'), 'py_patients', ['last_name'], unique=False)
    op.create_index(op.f('ix_py_patients_site_id'), 'py_patients', ['site_id'], unique=False)
    op.create_table('py_prescribers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('practice_level', sa.String(length=30), nullable=False),
    sa.Column('npi', sa.String(length=20), nullable=True),
    sa.Column('dea', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('fax', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['py_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_py_prescribers_last_name'), 'py_prescribers', ['last_name'], unique=False)
    op.create_index(op.f('ix_py_prescribers_site_id'), 'py_prescribers', ['site_id'], unique=False)
    op.create_table('py_products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('drug_id', sa.String(length=36), nullable=False),
    sa.Column('ndc', sa.String(length=30), nullable=False),
    sa.Column('manufacturer', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['py_drugs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ndc')
    )
    op.create_index(op.f('ix_py_products_drug_id'), 'py_products', ['drug_id'], unique=False)
    op.create_table('py_staff',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['py_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_py_staff_site_id'), 'py_staff', ['site_id'], unique=False)
    op.create_table('py_audit',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=90), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['py_staff.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['py_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_py_audit_site_id'), 'py_audit', ['site_id'], unique=False)
    op.create_table('py_barcodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('value', sa.String(length=160), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['py_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('py_cycle_count_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('reviewed_by_id', sa.String(length=36), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('OPEN','SUBMITTED','APPROVED','REJECTED')"),
    sa.ForeignKeyConstraint(['created_by_id'], ['py_staff.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['py_staff.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['py_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_py_cycle_count_sessions_site_id'), 'py_cycle_count_sessions', ['site_id'], unique=False)
    op.create_table('py_prescriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('prescriber_id', sa.String(length=36), nullable=False),
    sa.Column('drug_id', sa.String(length=36), nullable=False),
    sa.Column('rx_number', sa.String(length=30), nullable=False),
    sa.Column('sig', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('refills_allowed', sa.Integer(), nullable=False),
    sa.Column('refills_used', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('held_from', sa.String(length=30), nullable=True),
    sa.Column('do_not_fill_before', sa.String(length=10), nullable=True),
    sa.Column('expiration_date', sa.String(length=10), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0 AND refills_used >= 0 AND refills_allowed >= 0'),
    sa.ForeignKeyConstraint(['drug_id'], ['py_drugs.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['py_patients.id'], ),
    sa.ForeignKeyConstraint(['prescriber_id'], ['py_prescribers.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['py_sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'rx_number')
    )
    op.create_index(op.f('ix_py_prescriptions_site_id'), 'py_prescriptions', ['site_id'], unique=False)
    op.create_table('py_purchase_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('vendor', sa.String(length=180), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('OPEN','PARTIAL','RECEIVED','CANCELLED')"),
    sa.ForeignKeyConstraint(['created_by_id'], ['py_staff.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['py_sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'reference')
    )
    op.create_index(op.f('ix_py_purchase_orders_site_id'), 'py_purchase_orders', ['site_id'], unique=False)
    op.create_table('py_recall_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('lot', sa.String(length=100), nullable=True),
    sa.Column('reference', sa.String(length=140), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('closed_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('ACTIVE','CLOSED')"),
    sa.ForeignKeyConstraint(['closed_by_id'], ['py_staff.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['py_staff.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['py_products.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['py_sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'reference')
    )
    op.create_index(op.f('ix_py_recall_cases_site_id'), 'py_recall_cases', ['site_id'], unique=False)
    op.create_table('py_stock',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('lot', sa.String(length=100), nullable=False),
    sa.Column('expires', sa.String(length=10), nullable=False),
    sa.Column('on_hand', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('reserved', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('quarantined', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.CheckConstraint('on_hand >= 0 AND reserved >= 0 AND quarantined >= 0'),
    sa.CheckConstraint('reserved + quarantined <= on_hand'),
    sa.ForeignKeyConstraint(['product_id'], ['py_products.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['py_sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'product_id', 'lot', 'expires')
    )
    op.create_index(op.f('ix_py_stock_site_id'), 'py_stock', ['site_id'], unique=False)
    op.create_table('py_cycle_count_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('stock_id', sa.String(length=36), nullable=False),
    sa.Column('counted_on_hand', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('baseline_on_hand', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('baseline_reserved', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('baseline_quarantined', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('movement_count', sa.Integer(), nullable=False),
    sa.Column('counted_by_id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('counted_on_hand >= 0 AND baseline_on_hand >= 0 AND movement_count >= 0'),
    sa.ForeignKeyConstraint(['counted_by_id'], ['py_staff.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['py_cycle_count_sessions.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['py_stock.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'stock_id')
    )
    op.create_index(op.f('ix_py_cycle_count_lines_session_id'), 'py_cycle_count_lines', ['session_id'], unique=False)
    op.create_table('py_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('prescription_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=25), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('storage_key', sa.String(length=180), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('encrypted', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('byte_size > 0 AND byte_size <= 26214400'),
    sa.ForeignKeyConstraint(['created_by_id'], ['py_staff.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['py_patients.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['py_prescriptions.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['py_sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_py_documents_prescription_id'), 'py_documents', ['prescription_id'], unique=False)
    op.create_index(op.f('ix_py_documents_site_id'), 'py_documents', ['site_id'], unique=False)
    op.create_table('py_dur_issues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prescription_id', sa.String(length=36), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=70), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['prescription_id'], ['py_prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_py_dur_issues_prescription_id'), 'py_dur_issues', ['prescription_id'], unique=False)
    op.create_table('py_fills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prescription_id', sa.String(length=36), nullable=False),
    sa.Column('fill_number', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('billed_quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['prescription_id'], ['py_prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prescription_id', 'fill_number', 'attempt')
    )
    op.create_index(op.f('ix_py_fills_prescription_id'), 'py_fills', ['prescription_id'], unique=False)
    op.create_table('py_inventory_holds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('stock_id', sa.String(length=36), nullable=False),
    sa.Column('recall_id', sa.String(length=36), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('resolution_reason', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('resolved_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('ACTIVE','RELEASED','DISPOSED')"),
    sa.CheckConstraint('quantity > 0'),
    sa.ForeignKeyConstraint(['created_by_id'], ['py_staff.id'], ),
    sa.ForeignKeyConstraint(['recall_id'], ['py_recall_cases.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['py_staff.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['py_sites.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['py_stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_py_inventory_holds_recall_id'), 'py_inventory_holds', ['recall_id'], unique=False)
    op.create_index(op.f('ix_py_inventory_holds_site_id'), 'py_inventory_holds', ['site_id'], unique=False)
    op.create_index(op.f('ix_py_inventory_holds_stock_id'), 'py_inventory_holds', ['stock_id'], unique=False)
    op.create_table('py_inventory_movements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('stock_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=35), nullable=False),
    sa.Column('on_hand_delta', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('reserved_delta', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('quarantined_delta', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('before_snapshot', sa.Text(), nullable=False),
    sa.Column('after_snapshot', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['py_staff.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['py_sites.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['py_stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_py_inventory_movements_site_id'), 'py_inventory_movements', ['site_id'], unique=False)
    op.create_index(op.f('ix_py_inventory_movements_stock_id'), 'py_inventory_movements', ['stock_id'], unique=False)
    op.create_table('py_inventory_transfers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('from_site_id', sa.String(length=36), nullable=False),
    sa.Column('to_site_id', sa.String(length=36), nullable=False),
    sa.Column('source_stock_id', sa.String(length=36), nullable=False),
    sa.Column('received_stock_id', sa.String(length=36), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('shipped_by_id', sa.String(length=36), nullable=False),
    sa.Column('closed_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('IN_TRANSIT','RECEIVED','CANCELLED')"),
    sa.CheckConstraint('from_site_id <> to_site_id'),
    sa.CheckConstraint('quantity > 0'),
    sa.ForeignKeyConstraint(['closed_by_id'], ['py_staff.id'], ),
    sa.ForeignKeyConstraint(['from_site_id'], ['py_sites.id'], ),
    sa.ForeignKeyConstraint(['received_stock_id'], ['py_stock.id'], ),
    sa.ForeignKeyConstraint(['shipped_by_id'], ['py_staff.id'], ),
    sa.ForeignKeyConstraint(['source_stock_id'], ['py_stock.id'], ),
    sa.ForeignKeyConstraint(['to_site_id'], ['py_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_py_inventory_transfers_from_site_id'), 'py_inventory_transfers', ['from_site_id'], unique=False)
    op.create_index(op.f('ix_py_inventory_transfers_to_site_id'), 'py_inventory_transfers', ['to_site_id'], unique=False)
    op.create_table('py_purchase_order_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('ordered', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('received', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.CheckConstraint('ordered > 0 AND received >= 0 AND received <= ordered'),
    sa.ForeignKeyConstraint(['order_id'], ['py_purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['py_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'product_id')
    )
    op.create_index(op.f('ix_py_purchase_order_lines_order_id'), 'py_purchase_order_lines', ['order_id'], unique=False)
    op.create_table('py_claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fill_id', sa.String(length=36), nullable=False),
    sa.Column('payer', sa.String(length=120), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('billed_quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['fill_id'], ['py_fills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fill_id', 'sequence')
    )
    op.create_index(op.f('ix_py_claims_fill_id'), 'py_claims', ['fill_id'], unique=False)
    op.create_table('py_document_annotations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('prescription_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('x', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('y', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('width', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('height', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('supersedes_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'SUPERSEDED')"),
    sa.CheckConstraint('x + width <= 1.000001 AND y + height <= 1.000001'),
    sa.CheckConstraint('x >= 0 AND y >= 0 AND width >= 0.01 AND height >= 0.01'),
    sa.ForeignKeyConstraint(['created_by_id'], ['py_staff.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['py_documents.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['py_prescriptions.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['py_sites.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['py_document_annotations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supersedes_id')
    )
    op.create_index(op.f('ix_py_document_annotations_document_id'), 'py_document_annotations', ['document_id'], unique=False)
    op.create_index(op.f('ix_py_document_annotations_prescription_id'), 'py_document_annotations', ['prescription_id'], unique=False)
    op.create_index(op.f('ix_py_document_annotations_site_id'), 'py_document_annotations', ['site_id'], unique=False)
    op.create_table('py_fill_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fill_id', sa.String(length=36), nullable=False),
    sa.Column('stock_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['fill_id'], ['py_fills.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['py_stock.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fill_id', 'stock_id')
    )
    op.create_index(op.f('ix_py_fill_sources_fill_id'), 'py_fill_sources', ['fill_id'], unique=False)
    op.create_table('py_labels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fill_id', sa.String(length=36), nullable=False),
    sa.Column('bottle_number', sa.Integer(), nullable=False),
    sa.Column('bottle_count', sa.Integer(), nullable=False),
    sa.Column('ndc', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['fill_id'], ['py_fills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fill_id', 'bottle_number')
    )
    op.create_index(op.f('ix_py_labels_fill_id'), 'py_labels', ['fill_id'], unique=False)
    op.create_table('py_purchase_order_receipts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('line_id', sa.String(length=36), nullable=False),
    sa.Column('stock_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('invoice', sa.String(length=140), nullable=False),
    sa.Column('received_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0'),
    sa.ForeignKeyConstraint(['line_id'], ['py_purchase_order_lines.id'], ),
    sa.ForeignKeyConstraint(['received_by_id'], ['py_staff.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['py_sites.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['py_stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_py_purchase_order_receipts_line_id'), 'py_purchase_order_receipts', ['line_id'], unique=False)
    op.create_index(op.f('ix_py_purchase_order_receipts_site_id'), 'py_purchase_order_receipts', ['site_id'], unique=False)
    op.create_table('py_recall_exposures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recall_id', sa.String(length=36), nullable=False),
    sa.Column('fill_id', sa.String(length=36), nullable=False),
    sa.Column('status_at_discovery', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fill_id'], ['py_fills.id'], ),
    sa.ForeignKeyConstraint(['recall_id'], ['py_recall_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recall_id', 'fill_id')
    )
    op.create_index(op.f('ix_py_recall_exposures_recall_id'), 'py_recall_exposures', ['recall_id'], unique=False)
    op.create_table('py_sales',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fill_id', sa.String(length=36), nullable=False),
    sa.Column('verified_identity', sa.Boolean(), nullable=False),
    sa.Column('signature_attested', sa.Boolean(), nullable=False),
    sa.Column('tender', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['fill_id'], ['py_fills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fill_id')
    )
    op.create_table('py_will_call',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fill_id', sa.String(length=36), nullable=False),
    sa.Column('bag_barcode', sa.String(length=100), nullable=False),
    sa.Column('bin_name', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['fill_id'], ['py_fills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bag_barcode'),
    sa.UniqueConstraint('fill_id')
    )
    op.create_table('py_document_changes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('prescription_id', sa.String(length=36), nullable=False),
    sa.Column('annotation_id', sa.String(length=36), nullable=False),
    sa.Column('change_type', sa.String(length=30), nullable=False),
    sa.Column('what_changed', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('communication_method', sa.String(length=20), nullable=True),
    sa.Column('contacted_party', sa.String(length=200), nullable=True),
    sa.Column('authorizing_prescriber', sa.String(length=200), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('supersedes_id', sa.String(length=36), nullable=True),
    sa.Column('changed_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'SUPERSEDED')"),
    sa.ForeignKeyConstraint(['annotation_id'], ['py_document_annotations.id'], ),
    sa.ForeignKeyConstraint(['changed_by_id'], ['py_staff.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['py_prescriptions.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['py_sites.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['py_document_changes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('annotation_id'),
    sa.UniqueConstraint('supersedes_id')
    )
    op.create_index(op.f('ix_py_document_changes_prescription_id'), 'py_document_changes', ['prescription_id'], unique=False)
    op.create_index(op.f('ix_py_document_changes_site_id'), 'py_document_changes', ['site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Destructive downgrade is intentionally disabled for pharmacy data."""
    raise RuntimeError("Python schema downgrade disabled: restoration requires a reviewed backup/restore procedure")
