"""Add versioned payer profiles and immutable claim operations

Revision ID: fe722c185f29
Revises: 17d52add635c
Create Date: 2026-10-08 21:04:19.834218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe722c185f29'
down_revision: Union[str, Sequence[str], None] = '17d52add635c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('py_payer_billing_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('payer_name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('max_physical_sources', sa.Integer(), nullable=False),
    sa.Column('billing_ndc_strategy', sa.String(length=30), nullable=False),
    sa.Column('full_authorized_quantity', sa.Boolean(), nullable=False),
    sa.Column('effective', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("billing_ndc_strategy IN ('MAJORITY_NDC', 'FIRST_SCANNED')", name='ck_py_billing_strategy'),
    sa.CheckConstraint('max_physical_sources BETWEEN 1 AND 4', name='ck_py_billing_max_sources'),
    sa.CheckConstraint('version >= 1', name='ck_py_billing_version'),
    sa.ForeignKeyConstraint(['created_by_id'], ['py_staff.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['py_sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'payer_name', 'version', name='uq_py_billing_profile_version')
    )
    op.create_index('ix_py_billing_site_payer', 'py_payer_billing_profiles', ['site_id', 'payer_name'], unique=False)
    op.create_index(op.f('ix_py_payer_billing_profiles_site_id'), 'py_payer_billing_profiles', ['site_id'], unique=False)
    op.create_table('py_claim_operations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=True),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('payer_name', sa.String(length=120), nullable=False),
    sa.Column('selected_ndc', sa.String(length=30), nullable=False),
    sa.Column('billed_quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('source_snapshot', sa.Text(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("operation IN ('SYNTHETIC_PAID', 'SYNTHETIC_REVERSED')", name='ck_py_claim_op_type'),
    sa.CheckConstraint('billed_quantity > 0', name='ck_py_claim_positive'),
    sa.ForeignKeyConstraint(['actor_id'], ['py_staff.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['py_claims.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['py_payer_billing_profiles.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['py_sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id', 'operation', name='uq_py_claim_operation_kind')
    )
    op.create_index(op.f('ix_py_claim_operations_claim_id'), 'py_claim_operations', ['claim_id'], unique=False)
    op.create_index(op.f('ix_py_claim_operations_site_id'), 'py_claim_operations', ['site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Never delete financial / claims provenance in an automatic downgrade."""
    raise RuntimeError("Billing downgrade requires reviewed backup and restore")
